# Variables
@baseUrl = http://localhost:3003

# GET rooms
# @name getRooms
GET {{baseUrl}}/rooms

###

# POST rooms
# @name createRoom
POST {{baseUrl}}/rooms
content-type: application/json

{
  "name": "Room 1",
  "description": "Description 1"
}

###

@roomId = {{createRoom.response.body.$.id}}

# GET room questions
# @name getRoomQuestions
GET {{baseUrl}}/rooms/{{roomId}}/questions

###

# Create question
# @name createQuestion
POST {{baseUrl}}/rooms/20b8b650-62c7-4286-cca6-c3693b7c8811/questions
content-type: application/json

{
  "question": "Quando vai ser liberado o link do e-book?"
}

